config/routes.rb
Rails.application.routes.draw do
  get "documentary_film/index"
  get "documentary_film/create"
  get "documentary_film/new"
  get "serie/index"
  get "serie/create"
  get "serie/new"
  get "movie/index"
  get "movie/create"
  get "movie/new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  resources :movie, only: [:index, :new, :create]
  resources :serie, only: [:index, :new, :create]
  resources :documentary_film, only: [:index, :new, :create]

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documentary_film_controller.rb
class DocumentaryFilmController < ApplicationController
  def index
    @documentaries = DocumentaryFilm.all
  end

  def create
    @documentary = DocumentaryFilm.new(documentary_params)
    if @documentary.save 
      redirect_to documentary_film_path, notice: 'Documental creado exitosamente'
    else 
      render :new
    end
  end

  def new
    @documetary = DocumentaryFilm.new
  end


 
  private

  def documentary_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save 
      redirect_to @movie , notice: 'Película creada exitosamente'
    else 
      render :new
    end
  end

  def new
    @movie = Movie.new
  end

   private


  def movie_params
  params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/serie_controller.rb
class SerieController < ApplicationController
  def index
    @series = Serie.all
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save 
      redirect_to serie_path, notice: 'Serie creada exitosamente'
    else
      render :new
    end
  end

  def new
    @serie = Serie.new
  end



  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_film_helper.rb
module DocumentaryFilmHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/serie_helper.rb
module SerieHelper
end

app/views/documentary_film/create.html.erb
<h1>DocumentaryFilm#create</h1>
<p>Find me in app/views/documentary_film/create.html.erb</p>

app/views/documentary_film/index.html.erb
<h1>Documentales</h1>

<ul>
  <% @documentaries.each do |documentary| %>
    <p>Nombre: <%= documentary.name %></p>
    <p>Synopsis: <%= documentary.synopsis %></p>
    <p>Director: <%= documentary.director %></p> 
    <br>
  <% end %>
</ul>
<%= link_to 'Nuevo Documental', new_documentary_film_path %>

app/views/documentary_film/new.html.erb
<h1>Nuevo Documental</h1>



<%= form_with model: @documentary, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :synopsis %>
  <%= form.text_field :synopsis %><br>

  <%= form.label :director %>
  <%= form.text_field :director %><br><br>

  <%= form.submit 'Crear Documental' %>
<% end %>
  <br>
<%= link_to 'Volver', documentary_film_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Desafio Datos" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

app/views/movie/index.html.erb
<h1>Películas</h1>
<ul>
  <% @movies.each do |movie| %>
    <p>Nombre: <%= movie.name %></p>
    <p>Synopsis: <%= movie.synopsis %></p>
    <p>Director: <%= movie.director %></p> 
    <br>
  <% end %>
</ul>
<%= link_to 'Nueva Película', new_movie_path %>

app/views/movie/new.html.erb
<h1>Nueva Película</h1>
<%= form_with model: @movies, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :synopsis %>
  <%= form.text_field :synopsis %><br>

  <%= form.label :director %>
  <%= form.text_field :director %><br><br>

  <%= form.submit 'Crear Película' %>
<% end %>
  <br>
<%= link_to 'Volver', movie_index_path %>

app/views/serie/create.html.erb
<h1>Serie#create</h1>
<p>Find me in app/views/serie/create.html.erb</p>

app/views/serie/index.html.erb
<h1>Series</h1>
<ul>
  <% @series.each do |serie| %>
    <p>Nombre: <%= serie.name %></p>
    <p>Synopsis: <%= serie.synopsis %></p>
    <p>Director: <%= serie.director %></p> 
    <br>
  <% end %>
</ul>
<%= link_to 'Nueva Serie', new_serie_path %>

app/views/serie/new.html.erb
<h1>Nueva Serie</h1>
<%= form_with model: @series, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :synopsis %>
  <%= form.text_field :synopsis %><br>

  <%= form.label :director %>
  <%= form.text_field :director %><br><br>
  
  <%= form.submit 'Crear Serie' %>
<% end %>
  <br>
<%= link_to 'Volver', serie_index_path %>